### ISSUE TITLE
calculate mesh volume

### ISSUE THREAD

**Issue by jefferis** [zarquon42b/Rvcg#14]
Hello @zarquon42b, I was wondering if you might consider adding calculation of mesh volume some time. It looks fairly straightforward using vcg the code here as an example:

https://github.com/cnr-isti-vclab/vcglib/blob/a8e87662b63ee9f4ded5d4699b28d74183040803/apps/trimeshinfo/trimeshinfo.cpp#L815-L824

after checking for manifold status like so:

https://github.com/cnr-isti-vclab/vcglib/blob/a8e87662b63ee9f4ded5d4699b28d74183040803/apps/trimeshinfo/trimeshinfo.cpp#L786-L787

I know that Rvtkstatismo can do this, but it is still a bit of a beast to install – especially for end users. Thanks for considering!

**Comment by zarquon42b** [comment]
Hi Greg,
I'll have a look at it.

**Comment by jefferis** [comment]
Thanks!

**Comment by zarquon42b** [comment]
Hi Greg, I added a function called [vcgVolume](https://github.com/zarquon42b/Rvcg/commit/78015aecf6a6dc2c9c9f2628de2976e3b4b896cb)  in the latest master branch. Your referenced example code is pretty stale, however, and some of the called functions do not exist (anymore, I guess). So I just check manifoldness.

**Comment by zarquon42b** [comment]
UPDATE: I added checks for watertightness and coherent orientation and issue a warning if those conditions are not met (non-manifoldness leads to an error).

**Comment by jefferis** [comment]
Thanks so much @zarquon42b. This is is super! Unfortunately none of the meshes that I typicallyy work on pass the tests ...

I made a little extra change here:

https://github.com/zarquon42b/Rvcg/compare/master...jefferis:master

to add some more informative error messages. Now I need to figure out a good way to clean up my meshes! Not sure if you have any recommendations from inside Rvcg?

```
Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 25
  Non-manifold edges: 41

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 2
  Non-manifold edges: 15

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 29
  Non-manifold edges: 256

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 41
  Non-manifold edges: 344

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 1
  Non-manifold edges: 4

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 1
  Non-manifold edges: 4

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 3
  Non-manifold edges: 122050

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 1
  Non-manifold edges: 4

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 3
  Non-manifold edges: 122050

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 3
  Non-manifold edges: 122050

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 25
  Non-manifold edges: 152

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 3
  Non-manifold edges: 122050

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 0
  Non-manifold edges: 101948

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 4
  Non-manifold edges: 16

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 3
  Non-manifold edges: 122050

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 1
  Non-manifold edges: 4

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 38
  Non-manifold edges: 48

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 1
  Non-manifold edges: 20

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 3
  Non-manifold edges: 122050

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 24
  Non-manifold edges: 180

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 0
  Non-manifold edges: 810

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 8
  Non-manifold edges: 76

Error in vcgVolume(as.mesh3d(x)) : Mesh is not manifold
  Non-manifold vertices: 6
  Non-manifold edges: 28
```

**Comment by zarquon42b** [comment]
Hi,
thanks for the changes. I merged it into Rvcg. For the cleaning try: `vcgVolume(vcgClean(as.mesh3d(x),sel=0:6,iterate=T)) `

**Comment by jefferis** [comment]
That's great! Thank you. I wonder if it would be worth adding the clean step as an example to the function docs.

**Comment by zarquon42b** [comment]
Do you have a good example mesh, that I can include - unfortunately the example meshes in Rvcg are not watertight?

**Comment by jefferis** [comment]
@zarquon42b for including this in the latest CRAN release. One of the students in our group used it successfully today for the first time and was very happy with the results.
