### ISSUE TITLE
Uniform remesh quality

### ISSUE THREAD

**Issue by aharmer** [zarquon42b/Rvcg#16]
Hi, I'm wondering if you can help me understand an issue I am having with vcgUniformRemesh. I am trying to retopologise a mesh (~200k vertices) and am getting very different results depending on the software I use. When using the Instant Meshes app (https://github.com/wjakob/instant-meshes), I get a nice clean mesh, but when using vcgUniformRemesh I get some artefacts. I assume this is something to do with the different remeshing algorithms the two methods may be using, but do you know if there is a way to achieve smoother results with vcgUniformRemesh (vcgSmooth didn't have much effect).
Thanks,
Aaron.
![Screen Shot 2020-04-30 at 17 38 31](https://user-images.githubusercontent.com/10540385/80676466-ed932a00-8b0a-11ea-8d05-6b5e544dbfe5.png)

**Comment by zarquon42b** [comment]
Hi Aaron,
the left one looks smoothed and postprocessed (automatically). What do you mean by artifacts? The lines created by the marching cubes algorithm?
Can you send me the example data, so I can have a look at it. If using vcgSmooth, try another algorithm as taubin (default) as it is very conservative.

**Comment by aharmer** [comment]
Hi Stefan, thanks for the reply.
By artefacts I mean the stepped surface that is produced with vcgUniformRemesh. I tried some different smoothing options which improved the results, but nothing as clean as the left mesh without using a lot more vertices. I'll send you the original file I am trying to remesh via direct email as I am not able to make it public yet.
Thanks.
