### ISSUE TITLE
Geodesic distances

### ISSUE THREAD

**Issue by dfsp-spirit** [zarquon42b/Rvcg#17]
Thanks for making Rvcg! I wanted to ask whether you could consider adding geodesic distance computation.

A vcglib example from the official docs is [here](http://vcg.isti.cnr.it/vcglib/classvcg_1_1tri_1_1Geodesic.html) and [here](http://vcg.isti.cnr.it/vcglib/trimesh__geodesic_8cpp_source.html).

I tried to do it myself and submit a PR, but my knowledge on C++ template programming and Rcpp is very limited and I could not get it to work.

I [asked you about this](https://github.com/zarquon42b/RvtkStatismo/issues/9) a while ago in an RvtkStatismo issue and got it to work, but the installation required quite some effort and I cannot make RvtkStatismo a dependency of my package that is on CRAN.

**Comment by zarquon42b** [comment]
Hi @dfsp-spirit ,
[here](https://github.com/zarquon42b/Rvcg/commit/86c0ca8864190e289e2d2e8c4e77a30c9dee8701) you go. This is an iplementation of the Dijkstra-algorithm. It gives you the shorted geodesic distance to a point for each vertex. Please test and report back.

**Comment by zarquon42b** [comment]
Hi @dfsp-spirit ,
[here](https://github.com/zarquon42b/Rvcg/commit/86c0ca8864190e289e2d2e8c4e77a30c9dee8701) you go. This is an iplementation of the Dijkstra-algorithm. It gives you the shorted geodesic distance to a point for each vertex. Please test and report back.

**Comment by zarquon42b** [comment]
Update: I just pushed a wrapper function `vcgGeodist` to explicitly compute the geodesic distances between two 3D coordinates (projected) on a triangular surface mesh.

**Comment by dfsp-spirit** [comment]
Oh wow, that was fast. Thanks heaps, I'm off to test it...

**Comment by zarquon42b** [comment]
If you encounter me in procrastination mode, things can be fast ;)

**Comment by dfsp-spirit** [comment]
This looks great so far, I am testing it [here](https://github.com/dfsp-spirit/fsbrain/blob/brain_mesh_geodesic/web/examples/brain_surface_geodesic.R).

I'll post a visualization soon and compare the results to those from a Python and C implementation of geodesic distances.

**Comment by zarquon42b** [comment]
Nice, keep me posted. BTW it gives the exact same results as the VTK implementation.

**Comment by zarquon42b** [comment]
Here is another CAVEAT: this is actually not the geodesic path between the points but the pseudo-geodesic path (following the edges) between the two vertices closest to these points.

**Comment by dfsp-spirit** [comment]
Yes I know, I have read quite a bit about geodesic distances and seen various implementations and aproximative algorithms. That is fine with me. 

I'm currently computing the one-to-all vertices geodesic path length map for a larger mesh (160k verts), I'll add a plot once its done.

**Comment by zarquon42b** [comment]
I just also tested it and it takes 0.29 secs for a mesh with ~850.000 vertices.

**Comment by dfsp-spirit** [comment]
Yes, it is *very* fast.

**Comment by dfsp-spirit** [comment]
@zarquon42b This is amazing, thanks a lot.

I'll cite your Morpho/Rvcg paper given in`citation(Rvcg)` when I use it.

**Comment by zarquon42b** [comment]
I am glad that it works for you. Cool images ;)
