### ISSUE TITLE
`vcgUniformRemesh` freezes

### ISSUE THREAD

**Issue by stla** [zarquon42b/Rvcg#27]
Hello,

  This is the parameterization of the Boy surface.

```r
fx <- function(u,v){
  0.5*((2*(cos(u)*sin(v))^2-(sin(u)*sin(v))^2-(cos(v))^2)*((cos(u)*sin(v))^2+(sin(u)*sin(v))^2+(cos(v))^2)+2*(sin(u)*sin(v))*(cos(v))*((sin(u)*sin(v))^2-(cos(v))^2)+(cos(u)*sin(v))*(cos(v))*((cos(u)*sin(v))^2-(cos(v))^2)+(cos(u)*sin(v))*(sin(u)*sin(v))*((sin(u)*sin(v))^2-(cos(u)*sin(v))^2))
}
fy <- function(u,v){
  0.5*(sqrt(3)*(((sin(u)*sin(v))^2-(cos(v))^2)*((cos(u)*sin(v))^2+(sin(u)*sin(v))^2+(cos(v))^2)+(cos(v))*(cos(u)*sin(v))*((cos(v))^2-(cos(u)*sin(v))^2)+(cos(u)*sin(v))*(sin(u)*sin(v))*((sin(u)*sin(v))^2-(cos(u)*sin(v))^2)))
}
fz <- function(u,v){
  0.125*((cos(u)*sin(v))+(sin(u)*sin(v))+(cos(v)))*(((cos(u)*sin(v))+(sin(u)*sin(v))+(cos(v)))^3+4*((sin(u)*sin(v))-(cos(u)*sin(v)))*((cos(v))-(sin(u)*sin(v)))*((cos(u)*sin(v))-(cos(v))))
}

library(misc3d)
library(rgl)
tris <- parametric3d(fx, fy, fz,
             umin=0, umax=2*pi, vmin=0, vmax=2*pi, n=50, 
             engine = "none")

mesh00 <- misc3d:::t2ve(tris)
mesh0 <- tmesh3d(mesh00$vb, mesh00$ib)
mesh <- Rvcg::vcgUniformRemesh(mesh0)
```
At the last step, R is frozen.

**Comment by zarquon42b** [comment]
Hi,
on a first glance: the RAM usage goes way up.
I think the algorithm has a problem with the self-intersecting shape of the mesh. The algorithm involves a discretization of space and I would guess that the specific shape "confuses" the function regarding where outside and where inside is. 
The other remeshing algorithms like `vcgIsotropicRemeshing` work flawlessly.

**Comment by stla** [comment]
Thanks. Here is another example which never terminates. However this mesh is not self-intersecting, as far as I can see. This is this flower:

![Flower1](https://user-images.githubusercontent.com/4466543/149391426-7454a89b-dff4-4775-bb98-90ec6de5faa9.gif)

```r
library(misc3d)
library(rgl)

R <- function(u, v){
  cos(v)^2 * pmax(abs(sin(4*u)), 0.9 - 0.2*abs(cos(8*u)))
}
fx <- function(u, v){
  R(u, v) * cos(u) * cos(v)
}
fy <- function(u, v){
  R(u, v) * sin(u) * cos(v)
}
fz <- function(u, v){
  R(u, v) * sin(v) / 2
}

tris <- parametric3d(
  fx, fy, fz, umin = 0, umax = 2*pi, vmin = 0, vmax = 2*pi,
  engine = "none"
)

mesh00 <- misc3d:::t2ve(tris)
mesh0 <- tmesh3d(mesh00$vb, mesh00$ib)
mesh <- Rvcg::vcgUniformRemesh(mesh0)
```

**Comment by zarquon42b** [comment]
Hi,
if I run  your code, I get the error
```
In matrix(vertices, nrow = vrows) :
  data length [29415] is not a sub-multiple or multiple of the number of rows [4]
```
If I convert the data to mesh manually, I can see that the orientation of the faces is inconsistent. These type of inconsistencies cause exactly the problem of invsolvability to determine consistently an inside and outside.

This algorithm needs a consistent and sensible orientation of faces!

**Comment by stla** [comment]
Hmm maybe you get this error because you don't have the latest version of rgl? For me it works.

How do you see that the orientation is inconsistent if there's no normals? Is it given by the order of the indices?

I tried to generate the same mesh with Python and to import it to R, with no luck, same result. I also tried `Rvcg::vcgClean` with `sel=7`.

**Comment by stla** [comment]
There's something strange with this mesh. I already used the code below with another parameterization and got no issue. But with this parameterization of the flower, `vcgUniformRemesh` fails and `rgl::addNormals` throws some warnings.

```r
library(rgl)
library(Rvcg)

R <- function(u, v){
  cos(v)^2 * pmax(abs(sin(4*u)), 0.9 - 0.2*abs(cos(8*u)))
}
fx <- function(u, v){
  R(u, v) * cos(u) * cos(v)
}
fy <- function(u, v){
  R(u, v) * sin(u) * cos(v)
}
fz <- function(u, v){
  R(u, v) * sin(v) / 2
}
f <- function(u, v){
  c(fx(u, v), fy(u, v), fz(u, v))
}

fmesh <- function(nu, nv){
  vs <- matrix(NA_real_, nrow=3, ncol=nu*nv)
  u_ <- seq(0, 2*pi, length.out = nu+1)[-1L]
  v_ <- seq(0, 2*pi, length.out = nv+1)[-1L]
  for(i in 1:nu){
    for(j in 1:nv){
      vs[, (i-1L)*nv+j] <- f(u_[i], v_[j])
    }
  }
  tris1 <- matrix(NA_integer_, nrow = 3L, ncol = nu*nv)
  tris2 <- matrix(NA_integer_, nrow = 3L, ncol = nu*nv)
  for(i in 1L:nu){
    ip1 <- ifelse(i == nu, 1L, i+1L)
    for(j in 1L:nv){
      jp1 <- ifelse(j == nv, 1L, j+1L)
      tris1[, (i-1L)*nv+j] <- c((i-1L)*nv+j, (i-1L)*nv+jp1, (ip1-1L)*nv+j)
      tris2[, (i-1L)*nv+j] <- c((i-1L)*nv+jp1, (ip1-1L)*nv+jp1,(ip1-1L)*nv+j)
    }
  }
  #addNormals(
    tmesh3d(
    vertices = vs,
    indices = cbind(tris1, tris2),
    normals = NULL
  )
  #)
}
```
