### ISSUE TITLE
Import mesh file

### ISSUE THREAD

**Issue by Alireza-Mahalati** [zarquon42b/Rvcg#28]
Hi there,
I want to use a package and this is its description:
Cube counting for 3D mesh
Usage
cubes(mesh, L0, cubes, plot = FALSE)
Arguments
mesh  3D mesh with vertices	
L0  (Optional) The grain or resolution (i.e., smallest cube size)	
cubes  (Optional) A vector of number of cubes to be fitted at different scales.	
plot	 Plot number of filled cubes at different scales
how can I import my 3D mesh file (stl format)?
I tried to use rgl package  (readSTL(con = "E:/mesh", ascii = FALSE, plot = FALSE))
but I got following error: Error in file(con, if (ascii) "rt" else "rb") : 
cannot open the connection In addition: Warning message: In file(con, if (ascii) "rt" else "rb") :   cannot open file 'E:/mesh': Permission denied
Thanks!

**Comment by zarquon42b** [comment]
Hey, this is a issue tracker for my package and not a general purpose help hotline for R. None of your named functions is part of my package. Also please try to formulate your request more comprehensively and use proper formatting. The text above is pretty much not understandable, except that I guess that you have some problem with the readSTL function from rgl (which is not my package).
