### ISSUE TITLE
Angle of `vcgSphericalCap`

### ISSUE THREAD

**Issue by stla** [zarquon42b/Rvcg#29]
Hello,

  I find strange the angle of `vcgSphericalCap`. For me, `vcgSphericalCap(angleRad = pi/2)` should produce a hemisphere, while I expect that the effective result corresponds to an angle of pi/4. This is in agreement with the so-called [contact angle](https://mathworld.wolfram.com/SphericalCap.html) of the spherical cap.

**Comment by zarquon42b** [comment]
This is simply a wrapper of vcg::tri::SphericalCap()
https://github.com/cnr-isti-vclab/vcglib/blob/e4950d12e2db7f6ec3e587b06b2a0474b4f08d96/vcg/complex/algorithms/create/platonic.h#L355-L395
Please file a issue there if needed.
