### ISSUE TITLE
Rvcg::vcgCurve returns zeros

### ISSUE THREAD

**Issue by nialsiG** [zarquon42b/Rvcg#30]
OS: Windows 10
R version 4.2.0

For an unknown reason, vcgCurve returns arrays of zeros regardless of the surface used as *mesh*

Here is a reproductible example:

```{r}
library(Rvcg)
data(humface)
curv <- vcgCurve(humface)

summary(curv$meanitmax)
summary(curv$gaussitmax)
summary(curv$K1) #edit: works normally
summary(curv$k2) #edit: works normally

```

**Comment by zarquon42b** [comment]
Hi,
yes, this is an error introduced by some restructuring in vcglib. I'm on it.

**Comment by zarquon42b** [comment]
Please test: You can install it via
`devtools::install_github("zarquon42/Rvcg", ref="fix-vcgCurve")`

**Comment by nialsiG** [comment]
My mistake, you are right for principal curvatures K1 and K2. I edited the initial post.

After installing the correction, vcgCurve works perfectly. Well done, and thank you !
