### ISSUE TITLE
vcgCurve gives slightly different results than before

### ISSUE THREAD

**Issue by nialsiG** [zarquon42b/Rvcg#32]
Hello,
After the last correction to vcgCurve (thank you again!) I would like to report a difference with the previous behavior of the function... though I honnestly don't know if it can be qualified as an issue: 

- before, when I used Rvcg to display the mean curvature of a groovy surface, it returned negative values
- now, when I do the same, most of the groove is negative but some spots have positive values

Here is the reproducible example with mean curvature, look closely inside the grooves:

```{r}

mesh <- doolkit::dkmodel$complex
curv <- Rvcg::vcgCurve(mesh)$meanitmax
curvsign <- sign(curv)
doolkit::dkmap(mesh, curvsign, col = c("white", "red"), col.levels = 3)

```
I tried with gauss curvature, and it looks even more confusing to me:

```{r}

mesh <- doolkit::dkmodel$complex
curv <- Rvcg::vcgCurve(mesh)$gaussitmax
curvsign <- sign(curv)
doolkit::dkmap(mesh, curvsign, col = c("white", "red"), col.levels = 3)

```

OS: Windows 10
R: 4.2.0

**Comment by zarquon42b** [comment]
Hi @nialsiG ,
thanks for taking the time to report the bug.

I found the error I had forgotten an abs() statement in the C++ code. Running your examples now gives me those results (is this what you expected?). Please note that those values are the maxima (absolute values) of curvature for each face from its constituting vertices.
![RGL device 1  Focus _083](https://user-images.githubusercontent.com/1515863/168038239-4d13c6cc-30df-4960-ad02-260a8b7716e9.png)


![RGL device 1  Focus _084](https://user-images.githubusercontent.com/1515863/168038450-0b5d2ec1-8f65-424e-a31a-e8b6aa84cb68.png)

I pushed the changes into the [fix-vcgCurve](https://github.com/zarquon42b/Rvcg/tree/fix-vcgCurve) branch
Please test again.

**Comment by nialsiG** [comment]
That's a lot closer to what I expected.
I ran some tests on a handful of meshes and I can confirm that it solved the issue. Thank you for the fix!
