### ISSUE TITLE
Adding conda-forge recipe

### ISSUE THREAD

**Issue by dipterix** [zarquon42b/Rvcg#38]
@zarquon42b I'm adding your package Rvcg to conda-forge (https://github.com/conda-forge/staged-recipes/pull/22073). The goal is to allow conda users to install `Rvcg` via `conda install --channel conda-forge r-rvcg`

Can I add you to the maintainer list of that recipe in case there are any changes (such as dependence or compilers), you can edit and update the recipe? Normally you won't need to do anything when updating your package on CRAN. Conda-forge will automatically resolve and update the feedstock.

**Comment by zarquon42b** [comment]
Hey, this is awesome! Having stuff on multiple platform is really cool. Yes, you can add me to the maintainer list and maybe yourself too as you probably are more experienced in python as I am (I can find my way around).

**Comment by dipterix** [comment]
Thanks! It would be great if you could leave a comment showing you are willing to be one of the maintainers for this recipe in https://github.com/conda-forge/staged-recipes/pull/22073 . This is required by conda-forge in order for me to add anyone to the maintainer list. Something like "I would like to be added as maintainer" would suffice. (I'll make the changes once conda builders fix a compiler issue : )

**Comment by zarquon42b** [comment]
Hi, shall I post this statement into the issue tracker?

**Comment by dipterix** [comment]
I saw you posted the comment in PR. That's good enough. Thanks a lot!

Closing this "issue" now : )
