### ISSUE TITLE
Large volume & vcgIsosurface

### ISSUE THREAD

**Issue by Celli119** [zarquon42b/Rvcg#4]
Thresholding followed by mesh registration is really convenient  to make quick segmentations but for large volumes, which happen quite often, it requires too much RAM.
Then, the idea, would be to :
- split the volume into subvolumes (250 px cube for e.g.)
- apply the marching cubes algorithm (vcgIsosurface) for each of them separately
- merge meshes into a single one
- merge closed vertices
- clean everything

That's what I did but maybe there is a more suitable solution directly implemented in the vcg lib.

**Comment by zarquon42b** [comment]
Hi, this is a good idea. However, in order to obtain a watertight mesh, you would need to remesh the merged meshes.
The problem with vcglib is, that it is not very memory efficient, at least not the space discretization part.
In case your data is stored in files, you can try ```vtkTriangulate``` from RvtkStatismo.
