### ISSUE TITLE
Wish: allow vcgRaySearch() to return multiple intersections with a mesh

### ISSUE THREAD

**Issue by mirickmi** [zarquon42b/Rvcg#44]
Hello,

would it be possible for vcgRaySearch() to return the number of times a ray has intersected with a mesh? This could help to identify whether that ray comes from inside the mesh (uneven number of intersections) or from outside the mesh (even number of intersections). 

Kind regards,
Michael

**Comment by mirickmi** [comment]
Hi Stefan,

thanks for this wonderful package! This is exactly what I was looking for :-) I'd be very grateful if you can add this to the package. 

Didn't expect it to be that simple.

Just a minor addition to your Example:
-`require(rgl)` is missing to use the `wire3d()` function.
- `lms `was not previously defined. I replaced it with `x`.

Best regards,
Michael

**Comment by zarquon42b** [comment]
Fixed in [8d32287](https://github.com/zarquon42b/Rvcg/commit/8d322874079d465b61e7f985311ddac10c424724). 
I renamed the function to `raysearchMulti` to avoid confusion with `vcgRaySearch`.
