### ISSUE TITLE
vcgBallPivoting crashes in RStudio

### ISSUE THREAD

**Issue by marchtaylor** [zarquon42b/Rvcg#7]
This is not necessarily a problem with your package - but, so you know, vcgBallPivoting crashes RStudio
![clipboard01](https://cloud.githubusercontent.com/assets/8147731/17509091/91cd0bb4-5e18-11e6-9987-d133bdc6ac97.png)

**Comment by zarquon42b** [comment]
Hi @marchtaylor, 
what OS are you using? As this example is part of the CRAN checks, which it passes without error: https://cran.r-project.org/web/checks/check_results_Rvcg.html
Does it also happen when you run R with the default GUI or in a terminal?

**Comment by marchtaylor** [comment]
Hi @zarquon42b - No this does not happen in the default GUI, only in RStudio. This doesn't seem to be part of the checks, so maybe it doesn't catch it? Maybe this is a better question to address to RStudio themselves.

**Comment by zarquon42b** [comment]
I cannot reproduce the behaviour on my machine (using Rstudio), maybe there is something fishy with your installation. I will try windows as soon as I am back in office, as I don't have windows installed at home.
