### ISSUE TITLE
Rvcg is using the wrong source for the vcglibrary

### ISSUE THREAD

**Issue by cignoni** [zarquon42b/Rvcg#8]
I see that the Rvcg is stuck on version 5760 of the abandoned sourceforge svn repository.
The vcglibrary is currently maintained on github at:

https://github.com/cnr-isti-vclab/vcglib

The release branch is rather stable and it is aligned with the meshlab releases.

**Comment by zarquon42b** [comment]
Hi, thanks for the heads up.
after the latest release, I already updated the develop branch to the latest stable vcglib sources 5e8dc1365c124870ff6e20ce49819f162174748d. I am still pondering if including it as a submodule, however, I need some patches so that CRAN would accept my uploads.

**Comment by cignoni** [comment]
Great, I trusted the readme that were citing the old sourceforge site... 
If you have significant/reasonable modifications to the lib that could simplify the rvcg building process let us know...

**Comment by zarquon42b** [comment]
> Great, I trusted the readme that were citing the old sourceforge site...

Ah thanks, I will need to update the DESCRIPTION file.

>  If you have significant/reasonable modifications to the lib that could simplify the rvcg building process let us know...

I might actually get back to you on that matter ;)
